favicon: null
name: Zion
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.8802363
  lightness: 0.6836735
  brandStrength: 0.5
  brandColors:
    - '#0F1923'
    - '#026587'
    - '#029ACF'
    - '#88D0D7'
    - '#D7F1FB'
  rhythmicContrast: 0.3711063
typography_spectrum: 0.04614652437157929
layout_spectrum: 0.2443609
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
